/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2022-06-20 03:35:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class oficio_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1653093308068L));
    _jspx_dependants.put("jar:file:/C:/Users/TOSHIBA/OneDrive/Proyecto%20LP%20II/Proyecto%20LP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ProjectContratacion/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098729090000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	if(request.getSession().getAttribute("LISTA")==null)
		response.sendRedirect("login.jsp");

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Oficio</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.oficios{\r\n");
      out.write("\t background-color:#F8F3FA ;\r\n");
      out.write("\t padding: 20px;\r\n");
      out.write("\t border-radius: 9px;\r\n");
      out.write("\t margin-top: 13px;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\th1{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tmargin-top: 3rem;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t}\r\n");
      out.write("\t.oficiosDos{\r\n");
      out.write("\tbackground-color:#F8F3FA ;\r\n");
      out.write("\t\r\n");
      out.write("\t padding: 20px;\r\n");
      out.write("\t border-radius: 9px;\r\n");
      out.write("\t margin-top: 13px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.modal-header{\r\n");
      out.write("\t\tcolor:#fff;\r\n");
      out.write("\t\tbackground: #428bca;\r\n");
      out.write("\t\tdisplay: flex;\r\n");
      out.write("  \t\tjustify-content: center;\r\n");
      out.write("  \t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.help-block {\r\n");
      out.write("\t  \t\tcolor: red;\r\n");
      out.write("\t}\r\n");
      out.write("\t.form-group.has-error .form-control-label {\r\n");
      out.write("\t  color: red;\r\n");
      out.write("\t}\r\n");
      out.write("\t.form-group.has-error .form-control {\r\n");
      out.write("\t  border: 1px solid red;\r\n");
      out.write("\t  box-shadow: 0 0 0 0.2rem rgba(250, 16, 0, 0.18);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<!-- Text Gestionar Oficio -->\r\n");
      out.write("\t\t\t<h1>Gestionar Oficio</h1>\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t<!-- Nuevo Oficio y Criterios de Búsqueda -->\r\n");
      out.write("\t\t<div class=\"oficios d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<button type=\"button\" id =\"ejemplo\"class=\"btn btn-primary\" data-bs-toggle=\"modal\" data-bs-target=\"#staticBackdrop\">\r\n");
      out.write("\t\t  <img src=\"img/editar.png\" class=\"am\">Registrar Oficio\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\r\n");
      out.write("  \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- tabla -->\r\n");
      out.write("  \t\t<div class=\"oficiosDos\">\r\n");
      out.write("  \t\t\t<div class=\"mt-4\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t    \t<table id=\"example\" class=\"table table-striped\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t   <thead class=\"table-dark\" style=\"opacity:0.6;\">\r\n");
      out.write("\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t \t  \t<th>N°Solicitante</th>\r\n");
      out.write("\t\t                <th>N°Oficio</th>\r\n");
      out.write("\t\t                <th>Fecha de Ingreso</th>\r\n");
      out.write("\t\t                <th>Asunto</th>\r\n");
      out.write("\t\t                <th>Secretaria de Logistica</th>\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t                <th></th>\r\n");
      out.write("\t\t                <th></th>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t\t\t  </thead>\r\n");
      out.write("\t\t\t\t  <tbody>\r\n");
      out.write("\t\t        \t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("             \r\n");
      out.write("\t\t        </tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- MODAL PARA REGISTRAR-->\r\n");
      out.write("<div class=\"modal fade\" id=\"staticBackdrop\" aria-hidden=\"true\" aria-labelledby=\"staticBackdropLabel\" tabindex=\"-1\">\r\n");
      out.write("\t\t  <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("\t\t    <div class=\"modal-content\">\r\n");
      out.write("\t\t      <div class=\"modal-header\" style=\"color:black;background-color: #D6DBDF;\">\r\n");
      out.write("\t\t        <h5 class=\"modal-title\" id=\"#staticBackdropLabel\"> OFICIO</h5>\r\n");
      out.write("\t\t     <!-- >tyle=\"#FAF8F2\r\n");
      out.write("\t\t\t\tstyle=\"color:blue; background-color:#FAF8F2;\"-->\r\n");
      out.write("\t\t      </div> \r\n");
      out.write("\t\t      <div class=\"modal-body\">\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        <form id=\"idRegistrarOficio\" method=\"post\" action=\"ServletOficio?tipo=REGISTRAR\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"row justify-content-around\">\r\n");
      out.write("\t\t\t\t\t   <div class=\"form-group col-4\">\r\n");
      out.write("\t\t\t\t\t\t    <label for=\"exampleInputEmail1\" class=\"form-label\">N° Solicitante</label>\r\n");
      out.write("\t\t\t\t\t\t    <input type=\"number\" class=\"form-control\" name=\"codSoli\" id=\"idCodSoli\" readonly > \r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  \t<div class=\"form-group col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t    <button type=\"submit\" id=\"BuscarSolicitante\"class=\"btn btn-dark\"  \r\n");
      out.write("\t\t\t\t\t\t\t    data-bs-toggle=\"modal\" data-bs-target=\"#staticBackdrop\" style=\"border: 20px ; \" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\tBuscar Solicitante\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t <div class=\"form-group col-4\">\r\n");
      out.write("\t\t\t \t\t\t  <label for=\"exampleInputEmail1\" class=\"form-label\">N° Oficio</label>\r\n");
      out.write("\t\t\t\t\t    <input type=\"text\" class=\"form-control\" name=\"codOficio\" id=\"idCodigoOfi\" value=\"\">\r\n");
      out.write("\t\t\t\t\t  \t\r\n");
      out.write("    \r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\" form-group col-4\">\r\n");
      out.write("\t\t\t\t\t    <label for=\"exampleInputEmail1\" class=\"form-label\">Fecha de registro</label>\r\n");
      out.write("\t\t\t\t\t    <input type=\"date\" class=\"form-control\" name=\"fechaOfi\" id=\"idFechaOfi\">\r\n");
      out.write("\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"form-group col-4\">\r\n");
      out.write("\t\t\t\t\t    <label for=\"exampleInputEmail1\" class=\"form-label\">Asunto</label>\r\n");
      out.write("\t\t\t\t\t    <input type=\"text\" class=\"form-control\" name=\"asunOfi\" id=\"idAsunOfi\"> \r\n");
      out.write("\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"form-group col-4\">\r\n");
      out.write("\t\t\t\t\t    <label for=\"exampleInputEmail1\" class=\"form-label\">Nombre Secretaria</label>\r\n");
      out.write("\t\t\t\t\t    <input type=\"text\" class=\"form-control\" name=\"nomSecre\" id=\"idNomSecre\">\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t   <div class=\"form-group\" style=\"margin-top: 5px;\">\r\n");
      out.write("\t\t\t\t\t   \t  <label for=\"exampleInputEmail1\" class=\"form-label\">Mensaje</label>\r\n");
      out.write("\t\t\t\t\t\t  <textarea class=\"form-control\" placeholder=\"Leave a comment here\" name=\"mensa\" id=\"idMensa\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t  <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t  \t<button type=\"submit\" class=\"btn btn-primary\">Guardar</button>\r\n");
      out.write("\t\t\t        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cerrar</button>\r\n");
      out.write("\t\t\t     \t </div>\r\n");
      out.write("\t\t\t     \t </div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<!-- MODAL PARA BUSCAR SOLICITANTE -->\r\n");
      out.write("\t\t\t     \t \r\n");
      out.write("\t\t\t\t\t<div class=\"modal fade\" id=\"modalBuscarSoli\"  data-bs-backdrop=\"static\"  aria-hidden=\"true\" aria-labelledby=\"staticBackdropLabel\" tabindex=\"-1\" tabindex=\"-1\">\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable\">\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t      <div class=\"modal-header\"  style=\"color:black;background-color: #D6DBDF;\">\r\n");
      out.write("\t\t\t\t\t\t        <h5 class=\"modal-title\" id=\"staticBackdropLabel\">BUSCAR SOLICITANTE</h5>\r\n");
      out.write("\t\t\t\t\t\t              <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("\t\t\t\t\t\t      \r\n");
      out.write("\t\t\t\t\t\t      </div>\r\n");
      out.write("    \t\t\t\t<div class=\"modal-body\">   \t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<table id=\"example2\" class=\"table table-striped\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t\t\t \t  <thead class=\"table-dark\" style=\"opacity:0.6;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t\t\t                <th>Código</th>        \r\n");
      out.write("\t\t\t\t\t\t                <th>Nombre</th>\r\n");
      out.write("\t\t\t\t\t\t                <th>Apellidos</th>\r\n");
      out.write("\t\t\t\t\t\t                <th>DNI</th>\r\n");
      out.write("\t\t\t\t\t\t                <th>Distrito</th>\t\t\t       \r\n");
      out.write("\t\t\t\t\t\t                <th>Tipo Contrato</th> \r\n");
      out.write("\t\t\t\t\t\t                <th>Acciones</th>\r\n");
      out.write("\t\t\t\t\t\t                <th></th>\r\n");
      out.write("\t\t\t\t\t\t           \r\n");
      out.write("\t\t\t\t\t\t            \r\n");
      out.write("\t\t\t\t\t            </tr>\r\n");
      out.write("\t\t\t\t\t\t\t  </thead>\r\n");
      out.write("\t\t\t\t\t\t\t  <tbody>\r\n");
      out.write("\t\t\t\t\t        \t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("             \r\n");
      out.write("\t\t\t\t\t\t        </tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("   \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t     </div>\t\t\t\t\t\t     \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- MODAL PARA ELIMINAR -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"modalEliminar\" data-bs-backdrop=\"static\" data-bs-keyboard=\"false\" tabindex=\"-1\" aria-labelledby=\"staticBackdropLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t  <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("\t\t    <div class=\"modal-content\">\r\n");
      out.write("\t\t      <div class=\"modal-header\" style=\"color:black;background-color: #D6DBDF;\">\r\n");
      out.write("\t\t        <h5 class=\"modal-title\" id=\"staticBackdropLabel\">Eliminar</h5>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t      <div class=\"modal-body\">\r\n");
      out.write("\t\t        <form id=\"idRegistrarOficio\" method=\"post\" action=\"ServletOficio?tipo=ELIMINAR\">\r\n");
      out.write("\t\t\t\t    <input type=\"hidden\" class=\"form-control\" name=\"codigoEliminar\" id=\"codigoEliminar\">\r\n");
      out.write("\t\t\t\t  <h4>¿Seguro de eliminar el oficio?</h4>\r\n");
      out.write("\t\t\t\t  <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t  \t<button type=\"submit\" class=\"btn btn-primary\"><img src=\"img/si.png\"></button>\r\n");
      out.write("\t\t\t        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\"><img src=\"img/rechazado.png\"></button>\r\n");
      out.write("\t\t\t      </div>\t\t\t  \r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- SCRIPT -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.bootcdn.net/ajax/libs/bootstrap-validator/0.4.0/js/bootstrapValidator.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    $('#example').DataTable();\r\n");
      out.write("    \r\n");
      out.write("} );\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    $('#example2').DataTable();\r\n");
      out.write("    \r\n");
      out.write("} );\r\n");
      out.write("$(document).on('click', '#ejemplo', function() {\r\n");
      out.write("    $('#staticBackdrop').modal('show');\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(document).on('click', '#BuscarSolicitante', function() {\r\n");
      out.write("    $('#modalBuscarSoli').modal('show');\r\n");
      out.write("});\r\n");
      out.write("//aisgnar evento click a todos los botones con nombre de clase \"btn-danger\"\r\n");
      out.write("$(document).on(\"click\",\".btn-danger\",function(){\r\n");
      out.write("\t//variable\r\n");
      out.write("\tlet cod;\r\n");
      out.write("\t//Obtener el codigo del oficio según el botón eliminar que se a pulsado\r\n");
      out.write("\tcod=$(this).parents(\"tr\").find(\"td\")[0].innerHTML;\r\n");
      out.write("\t//asignar a la caja con id \"codigoEliminar\" el valor de la variable \"cod\"\r\n");
      out.write("\t$(\"#codigoEliminar\").val(cod);\r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("//aisgnar evento click a todos los botones con nombre de clase \"btn-success\"\r\n");
      out.write("$(document).on(\"click\",\".btn-success\",function(){\r\n");
      out.write("\t//variables\r\n");
      out.write("\tlet cod;\r\n");
      out.write("\tcod=$(this).parents(\"tr\").find(\"td\")[1].innerHTML;\r\n");
      out.write("\t\r\n");
      out.write("\t$.get(\"ServletOficioJSON?codigo=\"+cod,function(response){\r\n");
      out.write("\t\t$(\"#idCodSoli\").val(response.codSoli);\r\n");
      out.write("\t\t$(\"#idCodigoOfi\").val(cod);\r\n");
      out.write("\t\t$(\"#idFechaOfi\").val(response.fechaOfi);\r\n");
      out.write("\t\t$(\"#idAsunOfi\").val(response.asuntoOfi);\r\n");
      out.write("\t\t$(\"#idNomSecre\").val(response.nomSecre);\r\n");
      out.write("\t\t$(\"#idMensa\").val(response.mens);\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\t\r\n");
      out.write("\t\r\n");
      out.write("})\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//aisgnar evento click a todos los botones con nombre de clase \"btn-success\"\r\n");
      out.write("$(document).on(\"click\",\".enviarCodigo\",function(){\r\n");
      out.write("\t//variables\r\n");
      out.write("\tlet cod;\r\n");
      out.write("\tcod=$(this).parents(\"tr\").find(\"td\")[0].innerHTML;\r\n");
      out.write("\t\r\n");
      out.write("\t$.get(\"ServletSolicitanteJSON?codigo=\"+cod,function(response){\r\n");
      out.write("\t\t$(\"#idCodSoli\").val(cod);\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\t\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- SCRIPT DE VALIDACIÓN DE REGISTRAR OFICIO -->\r\n");
      out.write("<script type=\"text/javascript\">    \r\n");
      out.write("    $(document).ready(function(){     \r\n");
      out.write("        $('#idRegistrarOficio').bootstrapValidator({      \r\n");
      out.write("        \t fields:{\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\t fechaOfi:{\r\n");
      out.write("        \t\t\t validators:{\r\n");
      out.write("     \t\t \t\t\tnotEmpty:{\r\n");
      out.write("     \t\t \t\t\t\tmessage:'Es obligatorio este campo'\r\n");
      out.write("     \t\t \t\t\t},\r\n");
      out.write("     \t\t \t\t\tregexp:{\r\n");
      out.write("     \t\t \t\t\t\tregexp:/^\\d{4}([\\-/.])(0?[1-9]|1[1-2])\\1(3[01]|[12][0-9]|0?[1-9])$/,\r\n");
      out.write("     \t\t \t\t\t\tmessage:'Ingrese como el formato YYYY-MM-DD'\r\n");
      out.write("     \t\t \t\t\t}\r\n");
      out.write("     \t\t \t\t}\r\n");
      out.write("     \t\t \t},\r\n");
      out.write("     \t\t \tasunOfi:{\r\n");
      out.write("    \t\t \t\tvalidators:{\r\n");
      out.write("    \t\t \t\t\tnotEmpty:{\r\n");
      out.write("    \t\t \t\t\t\tmessage:'Es obligatorio este campo'\r\n");
      out.write("    \t\t \t\t\t},\r\n");
      out.write("    \t\t \t\t\tregexp:{\r\n");
      out.write("    \t\t \t\t\t\tregexp:/^[a-zA-Z\\ñ\\Ñ\\s\\á\\é\\í\\ó\\ú\\Á\\É\\Í\\Ó\\Ú]{3,50}$/,\r\n");
      out.write("    \t\t \t\t\t\tmessage:'Ingrese solo letras'\r\n");
      out.write("    \t\t \t\t\t}\r\n");
      out.write("    \t\t \t\t}\r\n");
      out.write("    \t\t \t},\r\n");
      out.write("    \t\t \tnomSecre:{\r\n");
      out.write("    \t\t \t\tvalidators:{\r\n");
      out.write("    \t\t \t\t\tnotEmpty:{\r\n");
      out.write("    \t\t \t\t\t\tmessage:'Es obligatorio este campo'\r\n");
      out.write("    \t\t \t\t\t},\r\n");
      out.write("    \t\t \t\t\tregexp:{\r\n");
      out.write("    \t\t \t\t\t\tregexp:/^[a-zA-Z\\ñ\\Ñ\\s\\á\\é\\í\\ó\\ú\\Á\\É\\Í\\Ó\\Ú]{3,70}$/,\r\n");
      out.write("    \t\t \t\t\t\tmessage:'Ingrese solo letras'\r\n");
      out.write("    \t\t \t\t\t}\r\n");
      out.write("    \t\t \t\t\t\r\n");
      out.write("    \t\t \t\t}\r\n");
      out.write("    \t\t \t}\r\n");
      out.write("        \t }\r\n");
      out.write("        });   \r\n");
      out.write("\t\t\t\r\n");
      out.write("    });  \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /oficio.jsp(62,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.MENSAJE!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"alert alert-warning alert-dismissible fade show\" role=\"alert\">\r\n");
          out.write("\t\t\t\t  <strong>MENSAJE : </strong> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.MENSAJE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" \r\n");
          out.write("\t\t\t\t  <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /oficio.jsp(98,11) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.listOficio}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /oficio.jsp(98,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("row");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t            <tr>\r\n");
            out.write("\t\t\t\t          \t    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.codSoli}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.codOfi}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.fechaOfi}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.asuntoOfi}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.nomSecre}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t                \r\n");
            out.write("\t\r\n");
            out.write("\t\t\t\t                <td><button type=\"button\" class=\"btn btn-success\" \r\n");
            out.write("\t\t\t\t                \t\t\tdata-bs-toggle=\"modal\" data-bs-target=\"#staticBackdrop\"><img src=\"img/editar2.png\"></button></td>\r\n");
            out.write("\t\t\t\t                <td><button type=\"button\" class=\"btn btn-danger\" \r\n");
            out.write("\t\t\t\t                \t\t\tdata-bs-toggle=\"modal\" data-bs-target=\"#modalEliminar\"><img src=\"img/eliminar.png\"></button></td>\r\n");
            out.write("\t\t\t\t          </tr>\r\n");
            out.write("\t\t\t\t        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /oficio.jsp(206,14) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.buscarSolicitantes}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /oficio.jsp(206,14) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("row");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t            <tr>\r\n");
            out.write("\t\t\t\t\t\t\t                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.codSoli}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.nomSoli}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.apeSoli}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.dniSoli}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.distrito}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td> \r\n");
            out.write("\t\t\t\t\t\t\t\t                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.tipoContrato}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t                \r\n");
            out.write("\t\t\t\t\t\t\t                <td><button type=\"button\" class=\"enviarCodigo btn-info\" \r\n");
            out.write("\t\t\t\t\t\t\t                data-bs-toggle=\"modal\" data-bs-target=\"#staticBackdrop\"><img src=\"img/enviar.png\"></button></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t          </tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t       ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
